/* BODEN V2 */
const STORAGE_KEY="boden-v2";
const TEACHER_PIN="1234";
const initialData={classes:[{id:"1A",name:"1A",students:["Alma","Elias","Hugo","Liam","Maja","Noah","Olivia","William"]},{id:"1B",name:"1B",students:["Alice","Axel","Elsa","Isak","Leo","Nora","Sofia","Vera"]},{id:"2A",name:"2A",students:["Adam","Ella","Felix","Freja","Loke","Milo","Saga","Wilma"]},{id:"2B",name:"2B",students:["Albin","Ebba","Harry","Ida","Kalle","Lilly","Nils","Tilde"]}],items:[{id:"boll",name:"Boll",icon:"⚽",category:"Bollar",total:10,available:10},{id:"innebandy",name:"Innebandyklubba",icon:"🏑",category:"Sport",total:12,available:12},{id:"kon",name:"Kon",icon:"🔶",category:"Lek",total:20,available:20},{id:"hopprep",name:"Hopprep",icon:"〰️",category:"Lek",total:8,available:8},{id:"pingisrack",name:"Pingisrack",icon:"🏓",category:"Sport",total:6,available:6},{id:"rockring",name:"Rockring",icon:"⭕",category:"Lek",total:6,available:6},{id:"fotbollsvast",name:"Fotbollsväst",icon:"🦺",category:"Sport",total:15,available:15},{id:"frisbee",name:"Frisbee",icon:"🥏",category:"Lek",total:5,available:5}],loans:[]};
let data=load(),selectedClass=null,selectedStudent=null,selectedItem=null,teacherLogged=false;
const $=id=>document.getElementById(id);const views=[$("classesView"),$("studentsView"),$("itemsView"),$("loansView"),$("teacherView")];
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(initialData)}catch{return structuredClone(initialData)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function initials(n){return n.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()}
function date(v){return new Date(v).toLocaleString("sv-SE",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}
function toast(m){const t=$("toast");t.textContent=m;t.classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove("show"),2800)}
function show(v){views.forEach(x=>x.classList.add("hidden"));v.classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})}
function renderClasses(){const g=$("classGrid");g.innerHTML=data.classes.map(c=>`<button class="class-card" data-class="${esc(c.id)}"><div class="class-icon">🏫</div><div><strong>${esc(c.name)}</strong><span>${c.students.length} elever</span></div></button>`).join("");g.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedClass=data.classes.find(c=>c.id===b.dataset.class);$("classTitle").textContent=`Klass ${selectedClass.name}`;$("studentSearch").value="";renderStudents();show($("studentsView"))})}
function renderStudents(){if(!selectedClass)return;const q=$("studentSearch").value.toLowerCase().trim();const students=selectedClass.students.filter(s=>s.toLowerCase().includes(q));$("studentGrid").innerHTML=students.length?students.map(s=>{const n=data.loans.filter(l=>!l.returned&&l.classId===selectedClass.id&&l.student===s).length;return `<button class="student-card" data-student="${esc(s)}"><div class="avatar">${initials(s)}</div><div class="student-info"><strong>${esc(s)}</strong><span>${n?n+" aktivt lån":"Inga aktiva lån"}</span></div><div class="arrow">→</div></button>`}).join(""):`<div class="empty-state"><div>🔎</div><strong>Ingen elev hittades</strong><span>Testa ett annat namn.</span></div>`;$("studentGrid").querySelectorAll("button").forEach(b=>b.onclick=()=>selectStudent(b.dataset.student))}
function selectStudent(s){selectedStudent=s;$("studentTitle").textContent=s;$("studentSubtitle").textContent=`Klass ${selectedClass.name} · Välj vad som ska lånas`;renderItems();show($("itemsView"))}
function renderItems(){$("itemGrid").innerHTML=data.items.map(i=>{const disabled=i.available<1;return `<button class="item-card" ${disabled?"disabled":""} data-item="${esc(i.id)}"><div class="item-icon">${i.icon}</div><div class="item-info"><strong>${esc(i.name)}</strong><span>${esc(i.category)}</span><small class="${i.available<=2?"low-stock":""}">${disabled?"Slut":`${i.available} av ${i.total} lediga`}</small></div><div class="arrow">${disabled?"—":"→"}</div></button>`}).join("");$("itemGrid").querySelectorAll("button:not(:disabled)").forEach(b=>b.onclick=()=>openLoan(b.dataset.item))}
function openLoan(id){selectedItem=data.items.find(i=>i.id===id);$("modalTitle").textContent="Låna ut";$("modalText").innerHTML=`<strong>${esc(selectedStudent)}</strong> i klass <strong>${esc(selectedClass.name)}</strong> vill låna <strong>${esc(selectedItem.name)}</strong>.`;$("confirmModal").classList.remove("hidden")}
function closeLoan(){$("confirmModal").classList.add("hidden");selectedItem=null}
function loan(){if(!selectedItem)return;const i=data.items.find(x=>x.id===selectedItem.id);if(!i||i.available<1)return toast("Saken är slut.");data.loans.push({id:crypto.randomUUID?crypto.randomUUID():Date.now()+"",classId:selectedClass.id,className:selectedClass.name,student:selectedStudent,itemId:i.id,itemName:i.name,icon:i.icon,borrowedAt:new Date().toISOString(),returned:false,returnedAt:null});i.available--;save();updateCount();closeLoan();renderItems();renderStudents();toast(`${i.name} utlånad till ${selectedStudent}`)}
function updateCount(){$("loanCount").textContent=data.loans.filter(l=>!l.returned).length}
function renderLoans(){const active=data.loans.filter(l=>!l.returned).sort((a,b)=>new Date(b.borrowedAt)-new Date(a.borrowedAt));$("loanList").innerHTML=active.length?active.map(l=>`<article class="loan-card"><div class="loan-item-icon">${l.icon}</div><div class="loan-info"><strong>${esc(l.itemName)}</strong><span>${esc(l.student)} · Klass ${esc(l.className)}</span><small>Utlånad ${date(l.borrowedAt)}</small></div><button class="return-btn" data-loan="${l.id}">Lämna tillbaka</button></article>`).join(""):`<div class="empty-state"><div>📦</div><strong>Inga aktiva lån</strong><span>Alla saker finns i boden.</span></div>`;$("loanList").querySelectorAll("[data-loan]").forEach(b=>b.onclick=()=>returnLoan(b.dataset.loan))}
function returnLoan(id){const l=data.loans.find(x=>x.id===id);if(!l||l.returned)return;l.returned=true;l.returnedAt=new Date().toISOString();const i=data.items.find(x=>x.id===l.itemId);if(i)i.available=Math.min(i.total,i.available+1);save();updateCount();renderLoans();if(teacherLogged)renderAdmin();toast(`${l.itemName} är tillbaka i boden`)}
function openTeacher(){if(teacherLogged){showTeacher();return}$("pinInput").value="";$("pinError").textContent="";$("pinModal").classList.remove("hidden");setTimeout(()=>$("pinInput").focus(),50)}
function showTeacher(){renderAdmin();show($("teacherView"))}
function adminTabs(){document.querySelectorAll(".admin-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".admin-panel").forEach(x=>x.classList.add("hidden"));b.classList.add("active");$("admin"+b.dataset.tab.charAt(0).toUpperCase()+b.dataset.tab.slice(1)).classList.remove("hidden")})}
function renderAdmin(){const active=data.loans.filter(l=>!l.returned).length;const borrowed=data.items.reduce((n,i)=>n+(i.total-i.available),0);$("statsGrid").innerHTML=`<div class="stat-card"><span>Aktiva lån</span><strong>${active}</strong><small>just nu</small></div><div class="stat-card"><span>Saker utlånade</span><strong>${borrowed}</strong><small>av ${data.items.reduce((n,i)=>n+i.total,0)}</small></div><div class="stat-card"><span>Elever</span><strong>${data.classes.reduce((n,c)=>n+c.students.length,0)}</strong><small>i ${data.classes.length} klasser</small></div><div class="stat-card"><span>Artiklar</span><strong>${data.items.length}</strong><small>i registret</small></div>`;renderDashboard();renderAdminItems();renderAdminClasses();renderHistory();adminTabs()}
function renderDashboard(){$("adminDashboard").innerHTML=`<div class="admin-card"><div class="admin-card-head"><div><h3>Aktiva lån</h3><p>Senaste utlåningarna</p></div><button class="primary-btn" id="quickItem">+ Ny sak</button></div>${data.loans.filter(l=>!l.returned).slice(-8).reverse().map(l=>`<div class="admin-row"><span class="row-icon">${l.icon}</span><div><strong>${esc(l.itemName)}</strong><small>${esc(l.student)} · ${esc(l.className)}</small></div><time>${date(l.borrowedAt)}</time></div>`).join("")||`<div class="empty-state">Inga aktiva lån.</div>`}</div>`;$("quickItem").onclick=()=>openItemForm()}
function renderAdminItems(){$("adminItems").innerHTML=`<div class="admin-card"><div class="admin-card-head"><div><h3>Inventarie</h3><p>Hantera saker och antal.</p></div><button class="primary-btn" id="addItem">+ Lägg till</button></div><div class="admin-table">${data.items.map(i=>`<div class="admin-row"><span class="row-icon">${i.icon}</span><div><strong>${esc(i.name)}</strong><small>${esc(i.category)} · ${i.available}/${i.total} lediga</small></div><div class="row-actions"><button class="mini-btn" data-edit-item="${i.id}">Redigera</button><button class="mini-btn danger" data-delete-item="${i.id}">Ta bort</button></div></div>`).join("")}</div></div>`;$("addItem").onclick=()=>openItemForm();document.querySelectorAll("[data-edit-item]").forEach(b=>b.onclick=()=>openItemForm(b.dataset.editItem));document.querySelectorAll("[data-delete-item]").forEach(b=>b.onclick=()=>deleteItem(b.dataset.deleteItem))}
function openItemForm(id=null){const i=id?data.items.find(x=>x.id===id):null;openAdminModal("SAK",i?"Redigera sak":"Lägg till sak",`<label>Namn<input id="fName" class="admin-input" value="${esc(i?.name||"")}"></label><label>Ikon<input id="fIcon" class="admin-input" value="${esc(i?.icon||"📦")}"></label><label>Kategori<input id="fCategory" class="admin-input" value="${esc(i?.category||"Övrigt")}"></label><label>Antal<input id="fTotal" class="admin-input" type="number" min="0" value="${i?.total??1}"></label>`,()=>{const total=Math.max(0,Number($("fTotal").value)||0),name=$("fName").value.trim();if(!name)return toast("Namn krävs.");if(i){const diff=total-i.total;i.name=name;i.icon=$("fIcon").value||"📦";i.category=$("fCategory").value.trim()||"Övrigt";i.total=total;i.available=Math.max(0,i.available+diff)}else data.items.push({id:"item-"+Date.now(),name,icon:$("fIcon").value||"📦",category:$("fCategory").value.trim()||"Övrigt",total,available:total});save();renderAdmin();renderItems();toast(i?"Saken uppdaterad":"Saken tillagd")})}
function deleteItem(id){const i=data.items.find(x=>x.id===id);if(!i)return;if(data.loans.some(l=>l.itemId===id&&!l.returned))return toast("Kan inte ta bort en sak som är utlånad.");if(confirm(`Ta bort ${i.name}?`)){data.items=data.items.filter(x=>x.id!==id);save();renderAdmin();renderItems();toast("Saken borttagen")}}
function renderAdminClasses(){$("adminClasses").innerHTML=`<div class="admin-card"><div class="admin-card-head"><div><h3>Klasser och elever</h3><p>Hantera skolans elever.</p></div><button class="primary-btn" id="addClass">+ Ny klass</button></div>${data.classes.map(c=>`<div class="admin-class"><div><strong>${esc(c.name)}</strong><span>${c.students.length} elever</span></div><button class="mini-btn" data-edit-class="${c.id}">Hantera</button></div>`).join("")}</div>`;$("addClass").onclick=()=>openClassForm();document.querySelectorAll("[data-edit-class]").forEach(b=>b.onclick=()=>openClassForm(b.dataset.editClass))}
function openClassForm(id=null){const c=id?data.classes.find(x=>x.id===id):null;openAdminModal("KLASS",c?`Hantera ${c.name}`:"Ny klass",`<label>Klassnamn<input id="cName" class="admin-input" value="${esc(c?.name||"")}"></label><label>Elever <span class="field-note">Ett namn per rad</span><textarea id="cStudents" class="admin-input admin-textarea">${esc(c?.students.join("\n")||"")}</textarea></label>`,()=>{const name=$("cName").value.trim(),students=$("cStudents").value.split("\n").map(x=>x.trim()).filter(Boolean);if(!name)return toast("Klassnamn krävs.");if(c){c.name=name;c.students=students}else data.classes.push({id:name.replace(/\s/g,"")+Date.now(),name,students});save();renderAdmin();renderClasses();toast(c?"Klassen uppdaterad":"Klassen skapad")})}
function renderHistory(){const history=[...data.loans].sort((a,b)=>new Date(b.borrowedAt)-new Date(a.borrowedAt));$("adminHistory").innerHTML=`<div class="admin-card"><div class="admin-card-head"><div><h3>Lånehistorik</h3><p>${history.length} registrerade lån</p></div></div>${history.map(l=>`<div class="admin-row"><span class="row-icon">${l.icon}</span><div><strong>${esc(l.itemName)}</strong><small>${esc(l.student)} · ${esc(l.className)}</small></div><span class="status-pill ${l.returned?"returned":"active"}">${l.returned?"Återlämnad":"Utlånad"}</span></div>`).join("")||`<div class="empty-state">Ingen historik ännu.</div>`}</div>`}
function openAdminModal(eyebrow,title,body,onSave){$("adminModalEyebrow").textContent=eyebrow;$("adminModalTitle").textContent=title;$("adminModalBody").innerHTML=body;$("adminModal").classList.remove("hidden");window._adminSave=onSave}
function closeAdminModal(){$("adminModal").classList.add("hidden");window._adminSave=null}
$("studentSearch").oninput=renderStudents;$("loansBtn").onclick=()=>{renderLoans();show($("loansView"))};$("teacherBtn").onclick=openTeacher;$("confirmLoan").onclick=loan;$("cancelModal").onclick=closeLoan;$("cancelPin").onclick=()=>$("pinModal").classList.add("hidden");$("confirmPin").onclick=()=>{if($("pinInput").value===TEACHER_PIN){teacherLogged=true;$("pinModal").classList.add("hidden");showTeacher()}else $("pinError").textContent="Fel PIN-kod."};$("pinInput").onkeydown=e=>{if(e.key==="Enter")$("confirmPin").click()};$("teacherLogout").onclick=()=>{teacherLogged=false;show($("classesView"));toast("Du har loggat ut")};$("cancelAdminModal").onclick=closeAdminModal;$("saveAdminModal").onclick=()=>{if(window._adminSave){window._adminSave();closeAdminModal()}};document.querySelectorAll("[data-back]").forEach(b=>b.onclick=()=>{if(b.dataset.back==="classes")show($("classesView"));else{renderStudents();show($("studentsView"))}});renderClasses();updateCount();